[package]
edition = "2021"
name    = "zkmarket"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ark-bn254 = "0.4.0"
ark-crypto-primitives = { version = "0.4.0", default-features = true, features = [
    "r1cs",
    "encryption",
    "crh",
    "merkle_tree",
] }
ark-ec = "0.4.2"
ark-ed-on-bn254 = { version = "^0.4.0", features = ["r1cs"] }
ark-ff = "0.4.2"
ark-groth16 = "0.4.0"
ark-poly = "0.4.2"
ark-r1cs-std = "0.4.0"
ark-relations = "0.4.0"
ark-serialize = "0.4.2"
ark-std = { version = "0.4.0", features = ["getrandom"] }
libc = "0.2"
num-bigint = "0.4"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

derivative = "2.2.0"
rand       = "0.8.5"

hex                = "0.4.3"
tracing            = { version = "0.1" }
tracing-subscriber = "0.2.0"

napi        = "2"
napi-derive = "2"

[dev-dependencies]
ark-bls12-377 = "0.4.0"
ark-bls12-381 = "0.4.0"
ark-cp6-782 = "0.4.0"
ark-ed-on-bls12-381 = { version = "^0.4.0", features = ["r1cs"] }
ark-mnt4-298 = { version = "0.4.0", default-features = false, features = [
    "r1cs",
    "curve",
] }
ark-mnt4-753 = { version = "0.4.0", default-features = false, features = [
    "r1cs",
    "curve",
] }
ark-mnt6-298 = { version = "0.4.0", default-features = false, features = [
    "r1cs",
] }
ark-mnt6-753 = { version = "0.4.0", default-features = false, features = [
    "r1cs",
] }
napi-build = "1"
num-bigint = "0.4.3"


[build-dependencies]
napi-build = "2"

[profile.release]
lto = true


[features]

zkmarketserver = []
