/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SnarkInput {
  cm: string
  cmWallet: string
  gRX: string
  gRY: string
  c1X: string
  c1Y: string
  ctK: string
  hK: string
  kData: string
  pkConsX: string
  pkConsY: string
  enaWriter: string
  r: string
  fee: string
  ctKKeyX: string
  ctKKeyY: string
  ctKX: string
  ctKR: string
  tkAddr: string
  tkId: string
}
export function testSnarkInput(input: SnarkInput): void
export function test2(): number
export function prove(input: SnarkInput): string
export function init(): void
