/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SnarkInput {
  rt: string
  nf: string
  cmAzeroth: string
  hk: string
  addrseller: string
  gRX: string
  gRY: string
  c1X: string
  c1Y: string
  ctK: string
  cm: string
  leafPos: string
  treeProof: Array<string>
  skseller: string
  kData: string
  pkbuyerX: string
  pkbuyerY: string
  r: string
  fee: string
  oazeroth: string
  ctKKeyX: string
  ctKKeyY: string
  ctKX: string
  ctKR: string
  tkAddr: string
  tkId: string
}
export function testSnarkInput(input: SnarkInput): void
export function test2(): number
export function test3(): number
export function testForPk(): void
export function prove(input: SnarkInput): string
